ecomapp/urls.py
from django.urls import path
from .views import *


app_name="ecomapp"
urlpatterns = [
    path("",HomeViews.as_view(), name="home"),
    path("allproduct/", AllProductsView.as_view(), name="allproduct"),
    path("productdetail/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", CheckoutView. as_view(), name="checkoutview"),
    path("register/",CustomerRegistratonView.as_view(),name="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name="cutomerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name="adminorderdetail"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),
    path("admin-order-<int:pk>-change/", AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),
    path("search/", SearchView.as_view(), name="search"),
    path("easypaisa-request/", EasypaisaRequestView.as_view(), name="easypaisarequest"),
]

ecomproject/urls.py
from django.conf import settings
from django.conf.urls.static import static  
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Admin(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    full_name=models.CharField(max_length=50)
    image=models.ImageField(upload_to="admins")
    mobile=models.CharField(max_length=20)

class Customer(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200)
    address=models.CharField(max_length=200, null=True, blank=True)
    joined_on=models.DateTimeField(auto_now_add=True)


class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)


    def __str__ (self):
        return self.title

class Product (models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    image=models.ImageField(upload_to="products")
    marked_price=models.PositiveIntegerField()
    selling_price=models.PositiveIntegerField()
    description=models.TextField()
    warrantly=models.CharField(max_length=300, null=True, blank=True)
    retrun_policy=models.CharField(max_length=300, null=True, blank=True)
    view_count=models.PositiveIntegerField(default=0)
    def __str__ (self):
        return self.title

class Cart(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total=models.PositiveIntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)
    def __str__ (self):
        return "Cart:" +str(self.id)
class CartProduct(models.Model):
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    rate=models.PositiveIntegerField()
    quantity=models.PositiveBigIntegerField()
    subtotal=models.PositiveBigIntegerField()
    def __str__ (self):
        return "Cart:" +str(self.cart.id) +"cardProduct:"+str(self.id)
    
ORDER_STATUS = (
    ('Order Received', 'Order Received'),
    ('Orer Processing', 'Order Processing'),
    ('On the way', 'On the way'),
    ('Order completed', 'Order completed'),
    ('Order Canceled', 'Order Canceled'),
)
METHOD=(
    ("Cash on Delivery", "Cash on Delivery"),
    ("Khalti", "Khalti"),
)
    
class Order (models.Model):
    
    cart=models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by=models.CharField(max_length=200)
    shipping_address=models.CharField(max_length=200)
    mobile=models.CharField(max_length=10)
    email=models.EmailField(null=True, blank=True)
    subtotal=models.PositiveBigIntegerField()
    discount=models.PositiveBigIntegerField()
    total=models.PositiveBigIntegerField()
    order_status=models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at=models.DateTimeField(auto_now_add=True)
    payment_method=models.CharField(max_length=20, choices=METHOD, default="Cash on Delivery")
    payment_completed=models.BooleanField(default=False, null=True, blank=True)

    def __str__ (self):
        return "Order:" +str(self.id)

templates/about.html
{% extends 'base.html'%}

{% block content%}
this is about page
{% endblock%}

templates/addtocart.html
{% extends 'base.html'%}


{% block title %} Add to Cart {% endblock%}
{% block content%}

<div class="container">
    <h3> Product added to cart sucessfully</h3>
</div>
{% endblock %}

templates/allproduct.html
{%extends 'base.html'%}

{% block content%}

<div class="container">

    <h3> All Products</h3> <hr>

    {% for cat in allcategories %}

    <h3> {{cat}} </h3>
    <div class="row mt-3">
        <div class= "m-4">

            {% for p in cat.product_set.all %}<hr>
            <div class="col-md-3" style="border: 1px solid black;">
                <h3><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h3>
                <img src="{{p.image.url}}" alt="" width=250 height=250>
                <P> Price: <strike> Rs.{{p.marked_price}}</strike> Rs.{{p.selling_price}}</p>  
                    <a href=""{% url 'ecomapp:addtocart' p.id %}"" class="btn btn-primary"> Add to  Cart </a> 
            </div>
        </div>    

            {%endfor%}
    </div>
        

    </div>


    {%endfor%}

    

</div>

{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <title> {% block title%} {% endblock %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    
</head>
<body>
    

        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Shopping Cart</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'ecomapp:home'%}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%url 'ecomapp:allproduct'%}">Categories</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{%url 'ecomapp:mycart'%}"> My Cart</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      My Account
                    </a>
                    <ul class="dropdown-menu">
                        {% if request.user.customer%}
                        welcome{{request.user.username}}
                        <a class="dropdown-item" href="{% url 'ecomapp:customerprofile'%}"> My Profile</a>
                        <a class="dropdown-item" href="{% url 'ecomapp:cutomerlogout' %}">Log Out</a>
                        {%else%}
                        <a class="dropdown-item" href="{%url 'ecomapp:customerregistration'%}"> Registration</a>
                        <a class="dropdown-item" href="{%url 'ecomapp:customerlogin'%}"> Login</a>
                        {% endif%}
                    </ul>
                  </li>
                 
                </ul>
                <form class="d-flex" role="search" action="{% url 'ecomapp:search' %}" method ="GET">
                  <input name="keyword" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" required>
                  <button class="btn btn-danger" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
          
          
    <hr>
    {%block content%} 
    {%endblock%}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    
</body>
</html>

templates/checkout.html
{%extends 'base.html'%}

{% block title %} Checkout {%endblock%}

{%block content%}


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3> Items in the cart</h3>
            <a href="{% url 'ecomapp:mycart' %}" > Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th> SN </th>
                        <th> Product </th>
                        <th> Rate </th>
                        <th> Quantity </th>
                        <th> Subtotal </th>
                        <th> Action </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td> {{forloop.counter}} </td>
                        <td> {{cp.product.title}} </td>
                        <td> {{cp.rate}}</td>
                        <td> {{cp.quantity}} </td>
                        <td> {{cp.subtotal}} </td>
                    </tr>
                    {% endfor%}
        </div>
                <div class="col-md-6">
                <h3> Checkout Form</h3>
                <form action="" method="POST">
                    {%csrf_token%}
                    {{form}}
                    <button class="btn btn-info"> Place Order</button>
                </form>
                </div>
        
    </div>

</div>
{% endblock %}

templates/contact.html
{%extends 'base.html'%}

{%block content%}

This is Contacte
{%endblock%}

templates/customerlogin.html
{%extends 'base.html'%}
{% block title %}Customer Login{% endblock%}

{% block content %}
<style>
    .errorlist{
        color:red;

    }
</style>
<div class="container">

    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3> Customer Registration From </h3> <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary"> login as a Cutomer </button>
            {% if error %}
            <li style="color: red;"> {{error}} </li>
            {%endif%}     
            

            </form>
            <P> or dont have account<a href="{% url 'ecomapp:customerregistration' %}{% if request.GET.next%}?next={{request.GET.next}}{%endif%}"> Register here </a> </p>
        </div>
    </div>
</div>
{% endblock %} 

templates/customerorderdetail.html
{%extends 'base.html'%}
{% load humanize%}

{% block title %} Order Detail {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div clas=" col-md-8 mx-auto">
            <h3> Order Detail </h3> <hr>
            <p> <span class="font-weight-bold"> Order ID: </span> @ORDER_{{ord_obj.id}} </p>
            <p> <span class="font-weight-bold"> Order Status: </span> @ORDER_{{ord_obj.order_status}} </p>
            <p> <span class="font-weight-bold"> Order On: </span> @ORDER_{{ord_obj.created_at}} ({{ord_obj.created_at| timesince}} ag)</p>
            <p> <span class="font-weight-bold"> Customer Informnation: </span> By{{ord_obj.ordered_by}},{{ord_obj.mobile}}</p>
            <p> <span class="font-weight-bold"> Shipping Address: </span> By {{ord_obj.shipping_address}}({{ord_obj.email}})</p>
            <h4> Ordered Items</h4>
            <table>
                <thead>
                    <tr>
                        <th> SN </th>
                        <th> Items </th>
                        <th> Rate</th>
                        <th> Quantity</th>
                        <th> Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="blank" href="{% url 'ecomapp:productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td> {{cp.subtotal}}j</td>
                    </tr>

                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                        <th>Rs {{ord_obj.total| intcomma}}/-</th>
                    </tr>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/customerprofile.html
{% extends 'base.html'%}

{% block title %} My Profile {% endblock %}

{% block content %}
<div class="continaer">
    <div class="row">
        <div class="col-md-5">
            <h3> Detail Information</h3>
            <p> <span>Name: </span>{{customer.full_name}}</p>
            <p> <span>UserName: </span>{{customer.user..username}}</p>
            <p> <span>Email: </span>{{customer.user.email}}</p>
            <p> <span>Address: </span>{{customer.address}}</p>
            <p> <span>Joined On: </span>{{customer.joined_on}}</p>
        </div>
        <div class="col-md-6">
            <h3> Preveious Orders </h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th> SN</th>
                        <th> Order Id</th>
                        <th> Amount </th>
                        <th> Orderd on </th>
                        <th> Status </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ord in orders %}
                        <tr>
                            <td> {{forloop.counter}}</td>
                            <td><a href="{% url 'ecomapp:customerorderdetail' ord.pk %}">  #order_{{ord.id}}</a></td>
                            <td> {{ord.total}}</td>
                            <td> {{ord.created_at|timesince}} ago</td>
                            <td> {{ord.order_status}}</td>
                        </tr>{% endfor %}
        </div>
    </div>
</div>
      




{% endblock %}

templates/customerregistration.html
{%extends 'base.html'%}
{% block title %}Customer Registration{% endblock%}

{% block content %}
<style>
    .errorlist{
        color:red;

    }
</style>
<div class="container">

    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3> Customer Registration From </h3> <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary"> Register as a Cutomer </button>

            </form>
            <P> Already account<a href="{% url 'ecomapp:customerlogin' %}"> Login here </a> </p>
        </div>
    </div>
</div>
{% endblock %} 

templates/home.html
{%extends 'base.html'%}
{% block title%} Home {% endblock %}

{% block content%}
<div class="container">
    <h1 class="text-center"> Wellcome to Swat</h1>
    <hr> 
    <div class="row mt-3">
        {% for p in product_list %}
        <div class="col-md-3 card">
            <div class="m-4">
            <h3>{{p.title}}</h3>
            <img src="{{p.image.url}}" alt="" width=250 style="height:200px; object-fit:contain;">
            <P> Price: <strike> Rs.{{p.marked_price}}</strike> Rs.{{p.selling_price}}</p>  
            <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary"> Add to  Cart </a> 
            </div>
        </div>
        {%endfor%}
        <div class="pagination">
            <span class="step-links">
                {% if product_list.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ product_list.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ product_list.number }} of {{ product_list.paginator.num_pages }}.
                </span>
        
                {% if product_list.has_next %}
                    <a href="?page={{ product_list.next_page_number }}">next</a>
                    <a href="?page={{ product_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %} my cart {% endblock%}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4> Items in my cart </h4> <hr>
            
            <table class="table">
                <thead>
                    <tr>
                        <th> SN </th>
                        <th> Product </th>
                        <th> Rate </th>
                        <th> Quantity </th>
                        <th> Subtotal </th>
                        <th> Action </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td> {{forloop.counter}} </td>
                        <td> {{cp.product.title}} </td>
                        <td> {{cp.rate}}</td>
                        <td> {{cp.quantity}} </td>
                        <td> {{cp.subtotal}} </td>
                        <td>
                            <a href = "{%url 'ecomapp:managecart' cp.id%}?action=inc" class="btn btn-primary"> + </a>
                            <a href = "{%url 'ecomapp:managecart' cp.id%}?action=dcr"class="btn btn-warning"> - </a>
                            <a href = "{%url 'ecomapp:managecart' cp.id%}?action=rmv" class="btn btn-danger" > x </a>
                            </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th> total</th>
                        <th> Rs.{{cart.total}}
                        {% if cart.cartproduct_set.all%}
                        <th>  <a href="{% url 'ecomapp:emptycart' %}"> Empty </a></th>
                        {% endif %}
                        </tr>
                        {% if cart.cartproduct_set.all%}
                        <tr>
                            <th> <a class="btn btn-info" href="{% url 'ecomapp:checkoutview' %}"> Checkout </a> </th>
                        </tr>
                        {% endif %}

                </tbody>
            </table>
        </div>
    </div>
</div>

            

{% endblock %}

templates/productdetail.html
{% extends 'base.html'%}
{%block content%}
<div class="container">
    <h3> Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-3">
            <img src="{{product.image.url}}" alt="" class="image-fluid" width=250>
        </div>
            <div class="col-md-3">
                <h4>{{product.title}}(Viewed {{product.view_count}}times)</h4>
                <h5>Category: {{product.category}}</h5>
                <h5> Price:<strike>{{product.marked_price  }}</strike>Rs.{{product.selling_price}}</h5>
                <a href="{% url 'ecomapp:addtocart' product.id %}"class="btn btn-info"> Add To Cart </a>
                <p class="text-info"> Warranty: {{product.warrantly}}</p>
                <p class="text-info">Return Policy: {{product.description}}</p>
                <p> {{product.descritpion}}</p>

            </div>
        </div>

    </div>
</div>
{%endblock%}

templates/search.html
{% extends 'base.html'%}

{% block title %} Search {% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3> Search Results for<span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-4">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-mid-8">
                    <h4> <a href="{%url 'ecomapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p> {{result.description | truncatewords:50}}</p>
                    <p> Return Policy:{{result.retrun_policy}}</p>
                    <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary"> Add to  Cart </a> 
                </div>

            </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}